/* global React, ReactBootstrap */

import { AccordionSection, MultipleCountContext } from '../../components/AccordionSection';

/**
 * NestedAccordionComponent
 *
 * Renders a nested accordion component by receiving feature tree data from R,
 * parsing it safely, and creating a nested accordion component rendered by React.
 *
 * Interestingly, the original implementation involved rendering of ReactBootstrap.Accordion,
 * however that proved to be cumbersome and non-intuitive for the user, so it was replaced
 * with a custom implementation based on the unordered list element.
 *
 * @param {Object} props - The component props.
 * @param {FeatureTree} props.data - The data for the accordion.
 * @param {string} props.namespace - The namespace for the accordion.
 * @param {boolean} props.multiple - Indicates if multiple selections are allowed.
 * @param {number} props.multipleLimit - The limit for the number of selections.
 * @param {AccordionMode} props.mode - The mode of the accordion.
 * @param {boolean} props.allowContinuous - Indicates if continuous selection is allowed.
 * @param {string[]} props.selectedVariables - The selected variables.
 * @param {string[]} props.selectedCategories - The selected categories.
 * @param {string[]} props.selectedFilterValues - The selected filter values.
 * @returns {React.ReactNode} The rendered nested accordion component.
 */
export function NestedAccordionComponent({
  data,
  namespace,
  multiple,
  multipleLimit,
  mode,
  allowContinuous,
  selectedVariables,
  selectedCategories,
  selectedFilterValues,
}) {
  // Name is a special property generated by the TreeNode library in R,
  // it should be removed so that a clean recursion can be done over
  // the same data structure on all recursive levels.
  delete data.name;

  const selectedVariablesSafe = Array.isArray(selectedVariables)
    ? selectedVariables
    : !!selectedVariables
    ? [selectedVariables]
    : [];

  const selectedCategoriesSafe = Array.isArray(selectedCategories)
    ? selectedCategories
    : !!selectedCategories
    ? [selectedCategories]
    : [];

  const selectedFilterValuesSafe = Array.isArray(selectedFilterValues)
    ? selectedFilterValues
    : !!selectedFilterValues
    ? [selectedFilterValues]
    : [];

  const [values, setValues] = React.useState(selectedVariablesSafe);

  const updateValues = (value, operation = 'add') => {
    let newValues;
    if (operation === 'add') {
      newValues = [...values, value];
    } else {
      newValues = values.filter((x) => x !== value);
    }
    newValues = [...new Set(newValues)];
    setValues(newValues);
  };

  return (
    <MultipleCountContext.Provider value={{ values, updateValues, multipleLimit }}>
      {multiple && mode === 'select' && (
        <p data-cy="selection-limit-message">
          Selected variables:{' '}
          <span style={{ color: values.length >= multipleLimit ? '#dc3545' : undefined }}>
            {values.length} out of {multipleLimit}
          </span>
        </p>
      )}
      <ul style={{ padding: 0 }}>
        {Object.keys(data).map((nextId) => (
          <AccordionSection
            key={nextId}
            id={nextId}
            parentId="root2"
            data={data}
            namespace={namespace}
            multiple={multiple}
            mode={mode}
            allowContinuous={allowContinuous}
            selectedVariables={selectedVariablesSafe}
            selectedCategories={selectedCategoriesSafe}
            selectedFilterValues={selectedFilterValuesSafe}
          />
        ))}
      </ul>
    </MultipleCountContext.Provider>
  );
}
